export const CHAIN_INDEXER = Symbol("CHAIN_INDEXER");
export const TRANSACTION_REPOSITORY = Symbol("TRANSACTION_REPOSITORY");
export const TRANSACTION_SYNC_REPOSITORY = Symbol("TRANSACTION_SYNC_REPOSITORY");
export const TRANSACTION_AVAILABILITY = Symbol("TRANSACTION_AVAILABILITY");
